### ISSUE TITLE
make:entity generate all nullable attributs 

### ISSUE THREAD

**Issue by corentinbaur** [symfony/maker-bundle#1175]
Hi, 

I don't understand why my entity has nullable attributs after generation

Have you the same behavior ? 
If yes, someone could be explain me ? 

I use PHP 8.1, makerBundle v1.45.0

```sh
 Class name of the entity to create or update (e.g. DeliciousPuppy):
 > TestEntity

 created: src/Entity/TestEntity.php
 created: src/Repository/TestEntityRepository.php
 
 Entity generated! Now let's add some fields!
 You can always add more fields later manually or by re-running this command.

 New property name (press <return> to stop adding fields):
 > label

 Field type (enter ? to see all types) [string]:
 > 

 Field length [255]:
 > 25

 Can this field be null in the database (nullable) (yes/no) [no]:
 > 

 updated: src/Entity/TestEntity.php

 Add another property? Enter the property name (or press <return> to stop adding fields):
 > 


           
  Success! 
           
```

This command generate this php file

```php
<?php

namespace App\Entity;

use App\Repository\TestEntityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TestEntityRepository::class)]
class TestEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 25)]
    private ?string $label = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }
}
```

Why it don't generate : 

```php
<?php

namespace App\Entity;

use App\Repository\TestEntityRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TestEntityRepository::class)]
class TestEntity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 25)]
    private string $label;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }
}

```

**Comment by weaverryan** [comment]
Hi there!

This was done on purpose as a way to add types still be as friendly as possible to users. If you look at your proposed code, directly after instantiation, the label property will “not be initialized”. And calling getLabel() would result in an error. That’s why we decided to make the properties nullable and initialize them to null: this allows the getters to work immediately. This won’t please everyone, I realize :).

Cheers!

**Comment by ThomasLandauer** [comment]
I find this behavior irritating too. Some arguments:
* PHPStan is reporting:
    > Property App\Entity\TestEntity::$label type mapping mismatch: property can contain string|null but database expects string.
* > And calling getLabel() would result in an error.

    This is not a drawback, but the *desired behavior,* if somebody explicitly decides for the field to be not nullable.

* > this allows the getters to work immediately

    For me (and everybody else striving for clean code), it's the exact opposite: They don't work immediately, I have to fix them manually by making them non-nullable.

* If the "official" Symfony entity generator is producing inconsistent code, this will educate new users that this is the recommended way to do it.

I agree that the nullable topic is hard.  I even suggested earlier to make *everything* nullable by default (see https://github.com/symfony/maker-bundle/issues/687), to make forms work out of the box.
But the current implementation looks like "neither fish nor fowl" (i.e. inconsistent) to me.

**Comment by jorismak** [comment]
It does leave a lot of code to be 'fixed' just after scaffolding, which is annoying. (nullable removed everywhere the database is non-nullable, constructor added, the non-nullable properties added as parameters to the constructor, fixing the getter return type, and in case of non-nullable relations fix the removeXxxx() method that tries to set the property to null).

I thought it was to let the Symfony Form component play nice with an Entity object, because TextType has the habit of trying to push an empty field as null into the property (which errors out before validation can happen if you make the property non-nullable).

We actually had a little team meeting to discuss if we should just ignore the phpstan warnings about nullable / non-nullable mismatch between the PHP object and the ORM definition, and accept the defaults that MakerBundle gives these days. But that didn't feel nice with a lot of our team members.

In the end we learned that Symfony's TextType is (somehow?) one of the few form-types that really wants to set a null as 'empty data' when the field is left empty, and tries to call the setter with a null argument (which then gives an error).
If you do the same with an EntityType of IntegerType, the setter is simply never called (and the property uninitialized, like I expect). This way, the `$form->handleReqest($request);` line doesn't give an error, and the form validator has a chance to run, which then can neatly react to NotBlank() assertions to mark the form as invalid.

As this only appears to happen with the TextType formtype for now, a simple `'empty_data' => ''` in the formtype-options fixes it, which sounds like a better workaround compared to ignoring phpstan issues.

So we to let non-nullable ORM columns be non-nullable in PHP code, and force them to be set through the constructor. This way, the code is self-documenting, and team members taking over the project or jumping in at a later point can't make the mistake of not setting a required property. And we don't have to add phpstan ignore lines.

But somewhere, somehow this whole thing doesn't feel right. As if the PHP community hasn't yet figured out the 'correct best practise' about all this.

**Comment by GlucNAc** [comment]
@jorismak Interesting point of view.

What do you mean by :
> If you do the same with an EntityType of IntegerType, the setter is simply never called (and the property uninitialized, like I expect).

Actually, I have a NumberType field, which is mandatory and references a non nullable float field of an entity, with default value to 0.0 (set in php, not in the SQL attribute). The HTML5 validation is disabled on my form so it is possible to send a form with an empty value for that field. If the user do so, a fatal error is raised because Symfony tries to set a null value using a setter accepting only float value. Then the setter is called.

Otherwise, I'm OK if the user set 0, but I want him to set it intentionally, so I want to raise him an error if he has forgotten this field. Adding `empty_data = 0.0` did solve **partially** the trick of the setting null error. Indeed, when the form is returned, the field is prefilled with 0. So if I submit the form again, then the validation is OK, which is not what I'm expected.

Another point, if you place in the constructor every mandatory fields (which means they don't have a default value), it is gonna be quite verbose and repetitive when you pass your object to the form builder:

```php
$myObject = new MyObject('', 0.0, '', '', new DateTime());
$form = $this->createForm(FormType::class, $myObject);
```
To overcome this you can set default values, the you loose the point of forcing developers to get known the object logic, and you can face the problem I have gave before.

How did you manage these cases ?
