### ISSUE TITLE
Major version for PHP 8

### ISSUE THREAD

**Issue by jdevinemt** [symfony/maker-bundle#1285]
I see that from version 1.43 to 1.44 this package changed from requiring PHP 7 to PHP 8. Is there a reason the major version wasn't changed in this version? To me it seems like it should be a major revision, since it requires upgrading a major version of PHP. It would make sense for it to be a minor version if it also still supported PHP 7. Composer lists this package as outdated, but upgradable (since it's a minor version). But I can't actually update it because I am still on PHP 7. It doesn't even download the latest version where PHP 7 was still supported. So I'm stuck with an annoying red dependency in composer. Let me know if you need any more info.

**Comment by jrushlow** [comment]
Howdy @jdevinemt - We chose to stick with 1.x because bumping the PHP dependency of MakerBundle doesn't actually _break_ any functionality.  

> But I can't actually update it because I am still on PHP 7. It doesn't even download the latest version where PHP 7 was still supported.

You should be able to use `symfony/maker-bundle` up to `1.43` on PHP 7. If you're not able to upgrade to `1.43`, there is likely a version constraint with another package preventing that from happening rather than the PHP version itself. `composer why-not symfony/maker-bundle 1.43` will show any blockers.

Hope this helps!

**Comment by jdevinemt** [comment]
@jrushlow Thanks for the response and explanation. I wasn't really sure what the best practice was to determine whether a version should be considered major or minor, so this helps me get an idea. I hadn't used the `why-not` command in the Composer CLI before either. It's very handy!
