### ISSUE TITLE
feature / add translations generator

### ISSUE THREAD

**Issue by wtorsi** [symfony/maker-bundle#137]
Hi,
It will be great to add support a generation of the translation file. 
At this moment it can be done by creating custom Generator, because at this moment it is not possible to override existing file.

**Comment by sadikoff** [comment]
Hi @wtorsi, 
What do you mean under _generation of translation file_? There is `bin/console translation:update` command which parses app and writes translation files.

**Comment by javiereguiluz** [comment]
I think @sadikoff is right. Symfony already provides a powerful command to do this: https://symfony.com/doc/current/translation.html#extracting-translation-contents-and-updating-catalogs-automatically  If you were proposing to generate an empty XLIFF file ... I think it's better to not do that in this bundle because that kind of file is a bit generic and in this bundle we prefer to only generate Symfony code. Thanks!
