### ISSUE TITLE
[make:crud][Test] Create and Flush EntityManager when all entities are removed ?

### ISSUE THREAD

**Issue by HiroKX** [symfony/maker-bundle#1377]
When generating the test associated with a controller, the `setUp` method doesn't create an instance of the `EntityManager` and doesn't flush after removing all the entities in the manager. 

Is this expected behavior, or should we address it?

What we have now :
![image](https://github.com/symfony/maker-bundle/assets/57806687/118a3895-b70d-4fd8-b491-0c77803edf23)

How i fixed it : 
![image](https://github.com/symfony/maker-bundle/assets/57806687/4ba0f029-9cf4-4396-99a3-fcb2593ebea4)

**Comment by weaverryan** [comment]
Yup! Can you open a PR? And actually, we already have a template that is correct I think - https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php

The bug was introduced when we removed some methods from the repository generation. So I think the fix is:

* Remove this variable https://github.com/symfony/maker-bundle/blob/main/src/Maker/MakeCrud.php#L254
* But then keep all of the code as if this were `true`
* Delete the old template - https://github.com/symfony/maker-bundle/blob/main/src/Resources/skeleton/crud/test/Test.tpl.php - it will never be used

PR appreciated!
