### ISSUE TITLE
Fluent Api For Class Source Manipulator

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/maker-bundle#153]
Moved from: https://github.com/symfony/symfony/issues/26963
Originally created by @mnavarrocarter

-----

Hi everyone!

I've been working on a RestBundle recently that makes some heavy use of the Glorious Maker Bundle to easily scaffold a lot of the utilities that I've implemented in the bundle itself. I've found very useful classes like the `DoctrineEntityHelper` and the `ClassSourceManipulator`.

However, this last one only works pretty much with entities. So what I'm trying to propose here is to implement a fluent interface for the `ClassSourceManipulator` class.

Something along the lines of:

```php
<?php

$this->source->addMethod('someMethodName')
    ->addArgument('someMethodName', 'argumentName', 'argumentType');
```

I know my example is pretty vague. I'm working to come up with a good API myself, but I've been studying how the php parser works first. I think the best implementation will be one that holds the operations into the class state (like doctrine's query builder does) and then execute them with a method called `write` or something like that.

I think that the Maker Bundle will benefit greatly of a feature like this, and will allow developers to easily modify source code and make awesome automation tools.

**Comment by mnavarrocarter** [comment]
Thanks @javiereguiluz. My bad! :)

**Comment by weaverryan** [comment]
Hey @mnavarrocarter!

Happy to hear you're liking some of the internals, and I've been waiting for an issue like this.

First, an important note about all of this. All the classes in MakerBundle are actually currently marked with `@internal`, which means that you're not supposed to use them directly, because we do not guarantee that their API won't change. We've done this so that we can focus on improving the quality of the commands, without being burdened by maintaining the API of the internal tools. So, strictly speaking, classes like `ClassSourceManipulator` are not meant to be used.

And, because the bundle is still pretty young, and the PHP parsing stuff is so complex, I'm a bit worried about opening these up. Honestly, if you're interested, my *ideal* situation would be for someone like you to take our code and create a standalone library for source mutation. Then, in theory, MakerBundle could use *that*. We could also keep things inside the bundle, and remove the `@internal`, but I don't want to spend a lot of time adding features to it, unless we need those features for MakerBundle itself.

Cheers!

**Comment by mnavarrocarter** [comment]
Thanks @weaverryan!

I will try to create something on a standalone library and try to come up with the most comfortable api possible. For what I've been learning from the php parser is that it does a really good job by itself. I'll try to improve on it. Maybe you can mark this like WIP so I can remember? And will post here when I have something more or less functional.

Cheers!

**Comment by mnavarrocarter** [comment]
@fogs Yeah, that's what the maker bundle uses for creating php files. :)

**Comment by stof** [comment]
@fogs the ClassSourceManipulator mentionned in this issue is a higher-level API using this PHP-Parser internally.
