### ISSUE TITLE
Rest API CRUD

### ISSUE THREAD

**Issue by nicraMarcin** [symfony/maker-bundle#158]
Hello,
Are there any chances to introduce crud generation for API for Rest without form a and templates?

**Comment by sadikoff** [comment]
Maybe we can discuss it.

**Comment by nicraMarcin** [comment]
:) I would write it myself but for this time is to complex for me, Im begginer as programmer :/
If maker culd generate crud controller for api it would be fine. Later I can paste skeleton

**Comment by LeJeanbono** [comment]
API Platform can do this for you : https://api-platform.com/docs/core/operations

**Comment by nicraMarcin** [comment]
Thaks for link it looks well but I don't need the whole platrform with no needed functions, with functions which I'll newer use. I need pure symfony-flex with few short bundles for api

**Comment by leevigraham** [comment]
@LeJeanbono true, but I would like to see some skeleton controllers which deal with accepting json body in the request and serialising output.

**Comment by mnavarrocarter** [comment]
Maybe I can work on a pull request for this. Is really not that complex to modify the MakeController command with a `-r` flag so it can generate it based on an existing entity. Give me some time. :)

**Comment by dunglas** [comment]
Code generation for APIs usually lead to bad and difficult to maintain code. Security (enforcing OWASP best practices), performance, pagination, filtering, respect of existing standards... are not as easy as it seems.
The first (private) version of API Platform was a code generator based on FOSRest... And it was a bad idea.

I strongly encourage to use API Platform, Loopback, Django REST or other (dynamic) similar solutions. In all those solutions, you can enable/disable features you want.

**Comment by lyrixx** [comment]
I totally agree with @dunglas here

**Comment by nicraMarcin** [comment]
@weaverryan `make:controller` is very good but not everybody needs to create twig templates. Next days I'll prepare schema of that controller and then You'll decide to add command to maker or not ok?

**Comment by weaverryan** [comment]
@nicraMarcin I think that's a great idea. It's much more useful to talk about concrete code, than theoretical stuff :)

**Comment by weaverryan** [comment]
There’s one immediate issue, and it’s subjective. I personally don’t think that anyone should use FosRestBundle. It’s confusing, and has too many features. If you can figure out how to use it, fine, no problem. But I don’t recommend it, because it’s confusing, and so I’m-1 to generate any code using it. If the bundle were split into smaller, clearer pieces, that would be a different story :). 

I would only consider a REST controller that only uses core Symfony features. The question is, can we generate something “rich enough” by doing that?

**Comment by nicraMarcin** [comment]
Ok, @weaverryan what is wrong with FosRestBundle?

**Comment by weaverryan** [comment]
FOSRestBundle just has too many unrelated features. Some are better than others. But as a package, it's confusing to know what's going on. And, I think that people expect it to be a "cure all" for their API. It's not (ApiPlatform is better for this). So, even though it adds some nice things, if you give it to a beginner, they often see FOSRestBundle as THE best way to build an API, use all of its features, and get confused :). I'd love to see it broken into smaller bundles to help with this.

And, in your example, you're not using it for much. I don't think the custom route annotations give you much - e.g. `@Rest\Get`. I think that's just the same as `@Route(... methods="GET")`. The view handling, while cool at first, can be confusing, and very few people actually need an API the renders in multiple formats. So, I prefer to use the serializer and simply put it into a Response.

**Comment by nicraMarcin** [comment]
> And, in your example, you're not using it for much. I don't think the custom route annotations give you much - e.g. @Rest\Get. I think that's just the same as @Route(... methods="GET"). The view handling, while cool at first, can be confusing, and very few people actually need an API the renders in multiple formats. So, I prefer to use the serializer and simply put it into a Response.
I think that You could have right :) I use FOSRest for view and "atumatic" response conversion. And I admitt that this bundle has much features. so I'll consider to abandon FOSRest and create own service to serialize data.

**Comment by nicraMarcin** [comment]
I changed controller a little bit to not use FOSRest, now it looks:
**src/Controller/CompanyController.php**
```
<?php

namespace App\Controller;

use App\Entity\Company;
use App\Services\CompanyService;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api/company", name="api_company_")
 */
class CompanyController extends Controller
{

	/**
	 * @Route("", name="index", methods={"GET"})
	 *
	 * @param CompanyService $cs
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function index(CompanyService $cs)
	{
		// $this->denyAccessUnlessGranted('index');
		$companies = $cs->getAllCompanies();

		return JsonResponse::fromJsonString($cs->getSerializer()->serialize($companies, ['id', 'company']), 200, ['X-Total-Count' => count($companies)]);
	}

	/**
	 * @Route("/new", name="new", methods={"POST"})
	 *
	 * @param Request $request
	 * @param CompanyService $cs
	 * @return Company|string
	 */
	public function new(Request $request, CompanyService $cs)
	{
		// $this->denyAccessUnlessGranted('new');
		// TODO Check data integrity
		$data = json_decode($request->getContent(), true);

		return $cs->addCompany($data);
	}

	/**
	 * @Route("/{id}", name="show", methods={"GET"}, requirements={"id":"\d+"})
	 * @param Company $company
	 * @param CompanyService $cs
	 * @return JsonResponse
	 */
	public function show(Company $company, CompanyService $cs)
	{
		// $this->denyAccessUnlessGranted('view', $company);
		return JsonResponse::fromJsonString($cs->getSerializer()->serialize($company));
	}

	/**
	 * @Route("/{id}/edit", name="edit", methods={"PUT"}, requirements={"id":"\d+"})
	 * @param Request $request
	 * @param Company $company
	 * @param CompanyService $cs
	 * @return Company
	 */
	public function edit(Request $request, Company $company, CompanyService $cs)
	{
		// $this->denyAccessUnlessGranted('edit', $company);
		$data = json_decode($request->getContent(), true);

		return $cs->editCompany($company, $data);
	}

	/**
	 * @Route("/{id}", name="delete", methods={"DELETE"}, requirements={"id":"\d+"})
	 *
	 * @param Company $company
	 * @param CompanyService $cs
	 * @return array
	 */
	public function delete(Company $company, CompanyService $cs)
	{
		// $this->denyAccessUnlessGranted('edit', $company);

		return $cs->deleteCompany($company);
	}

}
```
**src/Services/CompanyService.php**
```
<?php

namespace App\Services;

use App\Entity\Company;
use App\Entity\User;
use App\Repository\CompanyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

/**
 * Class CompanyService
 * @package App\Services
 */
class CompanyService
{

	/**
	 * @var EntityManagerInterface
	 */
	private $em;
	/**
	 * @var CompanyRepository
	 */
	private $companyRepository;

	/**
	 * @var User|null|object
	 */
	private $user;

	private $serializer;

	const SERIALIZER_FORMAT = 'json';

	/**
	 * CompanyService constructor.
	 * @param EntityManagerInterface $entityManager
	 * @param CompanyRepository $repository
	 * @param TokenStorageInterface $tokenStorage
	 * @param SerializerService $serializer
	 */
	public function __construct(EntityManagerInterface $entityManager, CompanyRepository $repository, TokenStorageInterface $tokenStorage, SerializerService $serializer)
	{
		$this->em = $entityManager;
		$this->companyRepository = $repository;
		$this->user = $entityManager->getRepository(User::class)->findOneBy(['username' => $tokenStorage->getToken()->getUser()->getUsername()]);
		$this->serializer = $serializer;
	}

	/**
	 * @return string
	 */
	public function getAllCompanies()
	{
		return $this->companyRepository->findAll();
	}

	/**
	 * @param array $data
	 * @return Company
	 */
	public function addCompany(array $data)
	{

		if ($this->companyRepository->findOneByNipOrRegon(['nip' => $data['nip'], 'regon' => $data['regon']]))
			throw new HttpException(406, 'Company with given NIP and REGON exists');

		$data['user'] = $this->user;
		$data['accountant'] = $this->user;

		try {
			$company = new Company($data);
		} catch (\Exception $e) {
			throw new HttpException(406, $e->getMessage());
		}
		$this->em->persist($company);
		$this->em->flush();

		return $company;
	}

	/**
	 * @param Company $company
	 * @param array $data
	 * @return Company
	 */
	public function editCompany(Company $company, array $data)
	{
		// TODO implement edit entity from given data
		try {
			$this->em->flush();
		} catch (\Exception $e) {
			throw new  HttpException(406, $e->getMessage());
		}

		return $company;
	}

	/**
	 * @param Company $company
	 * @return array
	 */
	public function deleteCompany(Company $company)
	{
		try {
			$this->em->remove($company);
			$this->em->flush();
		} catch (\Exception $e) {
			throw new HttpException(406, $e->getMessage());
		}
		return [];
	}

	public function getSerializer()
	{
		return $this->serializer;
	}
}
```
and own serializer service to keep serialization logig in one place
**src/Services/SerializerService.php**
```
<?php
namespace App\Services;

use JMS\Serializer\SerializationContext;
use JMS\Serializer\SerializerInterface;

/**
 * Class SerializerService
 * @package App\Services
 */
class SerializerService
{

	/**
	 *
	 */
	const SERIALIZERFORMAT = 'json';

	/**
	 * @var SerializerInterface|null
	 */
	private $serializer = null;

	/**
	 * SerializerService constructor.
	 * @param SerializerInterface $serializer
	 */
	public function __construct(SerializerInterface $serializer)
	{
		$this->serializer = $serializer;
	}

	/**
	 * @param $data
	 * @param array|null $groups
	 * @return string
	 */
	public function serialize($data, array $groups = null)
	{
		if ($groups)
		{
			return $this->serializer->serialize($data, self::SERIALIZERFORMAT, SerializationContext::create()->setGroups($groups));
		} else {
			return $this->serializer->serialize($data, self::SERIALIZERFORMAT);
		}
	}

	/**
	 * @param $data
	 * @param $type
	 * @return array|\JMS\Serializer\scalar|object
	 */
	public function deserialize($data, $type)
	{
		return $this->serializer->deserialize($data, $type, self::SERIALIZERFORMAT);
	}
}
```
Would it be ok?

**Comment by sadikoff** [comment]
I'm not very familiar with best practice for api controllers, but I think this example is too complicated for maker-bundle. Why not use a simpler way, like:
```php
<?php

namespace App\Controller;

use App\Entity\Record;
use App\Form\RecordType;
use App\Repository\RecordRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecordController extends Controller
{
    /**
     * @Route("/", name="record_index", methods={"GET"})
     */
    public function index(RecordRepository $repository): Response
    {
        return $this->json(['records' => $repository->findAll()]);
    }
    // and so on...
```

PS: Sorry for an incomplete example.

**Comment by nicraMarcin** [comment]
> PS: Sorry for an incomplete example.

Full example is not necessary :) I've deleted my comment because there was problems with trhowning errors which were thrown with `text/html` not json, so if this has to be API it must return json event with errors.
Your example doesn't take into account returning errors, Param converter when can't get from db thrown error which is responsed with text/html.

**Comment by sadikoff** [comment]
I think for api project user must implement something like `ExceptionListener::onKernelException` and convert html exceptions in json there. 

The only question is how we will validate obejcts through forms or directly(without forms, using validator service).

**Comment by sadikoff** [comment]
My simple generated crud api example: https://github.com/sadikoff/sf4-api-example
I think api-crud must generate only controller file without additional services, but maybe I'm wrong :)

**Comment by nicraMarcin** [comment]
> My simple generated crud api example: https://github.com/sadikoff/sf4-api-example
> I think api-crud must generate only controller file without additional services, but maybe I'm wrong :)

For me is almost well but IMHO good practice is doctrine logic to be seperated to service also serializer and when we add or edit entity we should return this new, updated value not only message. I think message isn't necssary because we get object, array of objects or error. so messages are unnecessary. With `$this->json()` we can get circural reference error, so using groups with returning data with api is also good practice.

**Comment by nicraMarcin** [comment]
> agreed and fixed

excelent :) Another issue is serializer to provide groups in serialization because in many cases this can lead to errors like circular reference. What if your record in entity has owner from User entity relatin ManyToOne? with default serialization `return $this->json($record);` this return record and full user data with roles, password too. So controller/service should take into account serializer groups. I think that group current Entity should name as enity class and related let's say 'related'. Then while serialize record wy should use array `group ['record', 'related']` and in entity annotate `@Groups{"record"}` in record enity, and in user entity add `@Groups{..., "related"}` a we'll get data we need

**Comment by dunglas** [comment]
Some comments on the controller (a Pull Request would be easier to review):

* I output a custom format. Symfony is committed to follow standards and open formats when they exist (don't reinvent the wheel). It's especially important in the API field because it's the key to have client libraries working with any server-side component, and from a broader perspective for the rise of the open web and the open data movement. Unfortunately this generated doesn't follow any of the existing standards for web API. There are 2 existing standards : JSON-LD (W3C standard) with its Hydra extension (W3C community draft) and HAL (RFC draft).  IMO Symfony must **not** creating custom API outputs instead of following standards. It's against popularizing the open web. For instance, the default format of Zend Apigility is HAL, the one of API Platform is JSON-LD (HAL is supported too). There are also some alternative, open formats for web APIs that are not standards but popular: JSONAPI and GraphQL (this one isn't REST). Both are already implemented in API Platform btw. If a code generator is included in this bundle (again, I think it's a bad idea for a lot of reasons, especially maintenance), it should at least follow an existing standard or format (HAL would be the easiest option, because the format is simple).
* `X-Total-Count` is not a standard at all, and the `X-` prefix for custom HTTP headers is deprecated: https://tools.ietf.org/html/rfc6648
* Security headers that are mandatory for secure REST APIs are not generated: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Security_headers
* You don't check the content-type of the request, this can lead to severe security issues: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Validate_content_types
* You don't use strict typing when parsing the JSON document ("Achieve an implicit input validation by using strong types like numbers, booleans, dates, times or fixed data ranges in API parameters
"), this can also lead to severe problems: https://www.owasp.org/index.php/REST_Security_Cheat_Sheet#Input_validation Btw, the Symfony Serializer has support for checking this, you should use it instead of `json_decode`
* `catch (\Exception $e)` is too broad, you must only catch expected exceptions
* Successful `POST` and `DELETE` methods should return the appropriate HTTP status code, not `200`: http://www.restapitutorial.com/httpstatuscodes.html
* Circular references must be handled
* IMO pagination must be enabled by default for lists or it can lead to a DDOS vector
* Serializing errors with a listener is a good idea, but there are more complicated cases to handle to hook properly in the Symfony exception handing system (take a look at the implementation in API Platform for example).
* There are standards for API error serialization too (Hydra and the API Problem RFC), the Symfony Serializer has native support for API Problem, it should be used.

Again, you will end up rebuilding something similar to API Platform (but with maintenance issues because of code generation and support for less features). I don't think it's a good idea to include such thing in this bundle. Or maybe a tiny, read-only HAL generator. But I'm not sure it is worth it.

**Comment by dunglas** [comment]
> @dunglas makes a lot of sense here. We should first try to make sure that using ApiPlatform is obvious and simple, even if you have a simple API use-case.

It is:

    composer create-project symfony/skeleton company-api && cd company-api
    composer require api

```php
/**
 * A human-readable description that will be used in the documentation.
 *
 * @ApiResource
 * @Entity
 */
class Company
{
    /**
      * @Id
      * @Column(type="guid")
      * @NotBlank
    */
    public $id;
   /**
     * @Column
     * @NotBlank
     */
    public $name;
}
```

You have a working, secure, and standard CRUD API. You can enable support for HAL, JSONAPI, YAML, CSV, XML and even GraphQL by adding some config options. Pagination, validation, and errors serialization are properly handled. You have all extensions points you may need (you can even replace Doctrine y your own persistance system easily). You can plug DDD-oriented code or implement CQRS if you want to. You have access to a bunch of builtin filters, you can let the client select exactly the fields it needs, order collections, disable or enable pagination, change the number of items per page (all of this is opt-in, not enabled by default). You can add authorization rules using Expression Language. Reuse all authentication strategies available for Symfony in core or a bundles (HTTP basic, JWT, OAuth...). Relations are handled properly (hypermedia), circular references too...

**Comment by nicraMarcin** [comment]
> composer require api

This installs whole api-platform and a lot  of stuff that probably will never been used. 
I only suggested to add to maker generating only controller for api + service to keep MCV seperated. Something simillary artisan in laravel does. 
No maker can generate whole crud controller for twig with full html and support with adding and the like, but why cannot do it for api?

**Comment by dunglas** [comment]
> This installs whole api-platform and a lot of stuff that probably will never been used.

This is not true. You must use API Platform's distribution to get the whole framework (including the admin component, the Progressive Web App Generator, the Schema.org's entity generator...). Using `composer require api`, you only get the [API Pack](https://github.com/api-platform/api-pack/blob/master/composer.json).

It includes tools commonly used for APIs (that you'll need to install even if you craft the API "by hand" enventualy):

* Doctrine annotations: you also need this dep for your generated code
* Doctrine ORM: you also need this dep for your generated code
* NelmioCorsBundle: you most likely will have to install this bundle anyway for your generated code
* Reflection DocBlock: it's actually a transient dep of Symfony's Serializer and PropertyInfo component, you will need it this code for your generated code (it allows to enforce some OWASP recommendations)
* Twig and the Symfony Asset components: those ones are only used to generate the documentations, you'll them if you install NelmioApiDoc or similar tools (it's most likely for any kind of API that you'll need at least a Swagger documentation), and it can be easily removed, see below.
* Symfony's Security Bundle and Expression Language component: you most likely will need it anyway to use the controller's `@Security` annotation, or to configure proper configuration, and it can be easily removed (see below)
* Symfony Validator: your generated code will most likely need it too, and it can be easily removed (see below)
* API Platform's core library: it contains PHP classes helpful to create APIs (including hypermedia normalizers) and the related Symfony bundle, classes can be used directly and for instance it's what NelmioApiDoc does, so if you install NelmioApiDoc to document your API created with the generator, you'll install API Platform Core anyway...

If you don't care about documentation, authorization, authentication and security (a tiny micro-service for instance), instead of `composer require api` type `composer require api-platform/core`. You will loose some features (including the Swagger documentation, a must have even for micro-services) but the set of dependencies installed will be very minimal (https://github.com/api-platform/core/blob/master/composer.json#L18), probably not more that the one needed for generated code anyway. And the actual thing is that the example in my previous comment **will still work**!

> Something simillary artisan in laravel does.

Laravel is an awesome tool for RAD... But not to create REST APIs. Thanks to `composer require api`, Symfony 4 is faster an better than Laravel for API development. Promoting a code generator instead would be a step backward.

> Now maker can generate whole crud controller for twig with full html and support with adding and the like, but why cannot do it for api?

Because... my previous comments :) You'll generate a bunch of hard to maintain code to generate a secure and standard API. It's why code generation is not the good solution for web APIs. It's also why most API frameworks, regardless of the programming language don't rely on code generation.

**Comment by theofidry** [comment]
>This installs whole api-platform and a lot of stuff that probably will never been used.

I think the core issue here is simply that: API-Platform feels too "heavy" for you. But the reality is, making a standardised and secure web API is hard, it's never going to be a json_encode/decode an entity output/input.

Also if you take a regular CRUD: it's using the Form component. Doesn't that feel heavy to you? It's one of the biggest Symfony component ever and one if not the most complex as well.

So IMO the issue is only the heaviness perceived which is unjustified: sure API-Platform have a lot of files, but it's not a problem and in terms of resources it's lightweight: it can run very well on a RasberryPi. The really heavy and costly part is generating all metadata & co which is only done either during dev or cache warmup. And it's not something you could skip unless you want to go back to a non-standardised API (which will likely require _a lot_ of duplicated code everywhere in the end)

**Comment by nicraMarcin** [comment]
Ok, I followed your sugesttions and installed pure `symfony/skeleton` and api
```
composer create-project symfony/skeleton company-api && cd company-api
composer require api
```
and the main issue of this topic remains: api platform doesn't have any controller maker for crud
```
marcin@dragon /tmp/company-api $ bin/console 
Symfony 4.0.9 (kernel: src, env: dev, debug: true)

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The Environment name. [default: "dev"]
      --no-debug        Switches off debug mode.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  about                                   Displays information about the current project
  help                                    Displays help for a command
  list                                    Lists commands
 api
  api:swagger:export                      Dump the Swagger 2.0 (OpenAPI) documentation
 assets
  assets:install                          Installs bundles web assets under a public directory
 cache
  cache:clear                             Clears the cache
  cache:pool:clear                        Clears cache pools
  cache:pool:prune                        Prunes cache pools
  cache:warmup                            Warms up an empty cache
 config
  config:dump-reference                   Dumps the default configuration for an extension
 debug
  debug:autowiring                        Lists classes/interfaces you can use for autowiring
  debug:config                            Dumps the current configuration for an extension
  debug:container                         Displays current services for an application
  debug:event-dispatcher                  Displays configured listeners for an application
  debug:router                            Displays current routes for an application
  debug:translation                       Displays translation messages information
  debug:twig                              Shows a list of twig functions, filters, globals and tests
 doctrine
  doctrine:cache:clear-collection-region  Clear a second-level cache collection region
  doctrine:cache:clear-entity-region      Clear a second-level cache entity region
  doctrine:cache:clear-metadata           Clears all metadata cache for an entity manager
  doctrine:cache:clear-query              Clears all query cache for an entity manager
  doctrine:cache:clear-query-region       Clear a second-level cache query region
  doctrine:cache:clear-result             Clears result cache for an entity manager
  doctrine:cache:contains                 Check if a cache entry exists
  doctrine:cache:delete                   Delete a cache entry
  doctrine:cache:flush                    [doctrine:cache:clear] Flush a given cache
  doctrine:cache:stats                    Get stats on a given cache provider
  doctrine:database:create                Creates the configured database
  doctrine:database:drop                  Drops the configured database
  doctrine:database:import                Import SQL file(s) directly to Database.
  doctrine:ensure-production-settings     Verify that Doctrine is properly configured for a production environment
  doctrine:generate:entities              [generate:doctrine:entities] Generates entity classes and method stubs from your mapping information
  doctrine:mapping:convert                [orm:convert:mapping] Convert mapping information between supported formats
  doctrine:mapping:import                 Imports mapping information from an existing database
  doctrine:mapping:info                   
  doctrine:query:dql                      Executes arbitrary DQL directly from the command line
  doctrine:query:sql                      Executes arbitrary SQL directly from the command line.
  doctrine:schema:create                  Executes (or dumps) the SQL needed to generate the database schema
  doctrine:schema:drop                    Executes (or dumps) the SQL needed to drop the current database schema
  doctrine:schema:update                  Executes (or dumps) the SQL needed to update the database schema to match the current mapping metadata
  doctrine:schema:validate                Validate the mapping files
 lint
  lint:twig                               Lints a template and outputs encountered errors
  lint:xliff                              Lints a XLIFF file and outputs encountered errors
  lint:yaml                               Lints a file and outputs encountered errors
 make
  make:auth                               Creates an empty Guard authenticator
  make:command                            Creates a new console command class
  make:controller                         Creates a new controller class
  make:crud                               Creates CRUD for Doctrine entity class
  make:entity                             Creates or updates a Doctrine entity class
  make:fixtures                           Creates a new class to load Doctrine fixtures
  make:form                               Creates a new form class
  make:functional-test                    Creates a new functional test class
  make:migration                          Creates a new migration based on database changes
  make:serializer:encoder                 Creates a new serializer encoder class
  make:subscriber                         Creates a new event subscriber class
  make:twig-extension                     Creates a new Twig extension class
  make:unit-test                          Creates a new unit test class
  make:validator                          Creates a new validator and constraint class
  make:voter                              Creates a new security voter class
 router
  router:match                            Helps debug routes by simulating a path info match
 security
  security:encode-password                Encodes a password.
 server
  server:run                              Runs a local web server
  server:start                            Starts a local web server in the background
  server:status                           Outputs the status of the local web server for the given address
  server:stop                             Stops the local web server that was started with the server:start command
 translation
  translation:update                      Updates the translation file

```
and maker still creates CRUD with html templates, not needed for api.

so even api-platform doesn't have CRUD creation.

**Comment by dunglas** [comment]
WDYT about #175 for that?

**Comment by nicraMarcin** [comment]
> WDYT about #175 for that?

For entity creation ok, but what about crud controller creation?

**Comment by Pierstoval** [comment]
@nicraMarcin you probably miss something, or am I?

Just execute these commands:

```bash
$ composer create-project symfony/skeleton api-project
# ...
$ cd api-project
$ composer req api orm
# Necessary for Doctrine & ApiPlatform
$ composer req server maker --dev
# Server is not mandatory, but it's nice for a basic dev setup. And maker is mandatory to  generate entities for your CRUD
$ php bin/console make:entity
# Create whatever entity you need
# You can add fields like you want, and update the object afterwards
$ vim src/Entity/Post.php
# Add "@ApiPlatform\Core\Annotation\ApiResource" annotation to your entity
# This is the only part where you write code in this example
# And it's only 2 lines
$ php bin/console server:start

 [OK] Server listening on http://127.0.0.1:8000

```

Now visit http://127.0.0.1:8000/api and you'll see this ready-to-use CRUD thanks to the auto-generated API documentation:

![image](https://user-images.githubusercontent.com/3369266/39672146-f9c3ebd8-5124-11e8-91fb-7f95ae7fc6e1.png)

What's the real problem? With this, you have a plug-and-play CRUD API, and it's using lots of awesome tools without you to setup anything. It's like EasyAdmin, but for APIs. I don't see the problem.

**Comment by theofidry** [comment]
>problem is that I don't need api-platform thats all. All i need is to generate 4 simple files.
I thought that could be fine if maker could do that with profit for every one. This is the reason that I created this issue.
If U think that feature is unnecessary in mater ok, there is no problem. You are symfony makre developers and U decide what to provide in maker and what not :)

The thing is, and you see it with the discussion above, it's not 4 simple files. Or at least if all you want is 4 simple files for a non standardised, insecure and unscalable API, I don't think this should be in the core or any API framework. There is no strict equivalence between a CRUD generating an HTML response and a JSON one, since how you consume it and the implications are different.

**Comment by nicraMarcin** [comment]
Ok, I admint that my API isn't standardiset bcause besides simple creating and serving entities must do some other logic. But I can't admit that my API is insecure :) I use security and voters for each operation :) I didn't use forms for checking and validating data, because I did it in service, but I think that I'll start using Forms like @sadikoff in his example suggested. I've started using symfony for almost half a year so I can tell what in Symfony I'm begginer and don't know all symfony features but all ahead of me

Ok, so I think that this issue can be closed :)

**Comment by Pierstoval** [comment]
To add my brick in the wall: it's not 4 simple files, because for each resource (a Post object for instance) you will need a few Controller actions, something to get serialization format, handle invalid resources in your POST/PUT requests, send standardized responses depending on the asked format (json, xml, json-ld, etc.), add Normalizers and Denormalizers to the serializer, add security options for non-safe methods, create a pagination for list, etc.

This is not "4 simple files", at all, because this is not "common" CRUD like you expect.

**Comment by javiereguiluz** [comment]
@nicraMarcin it's totally legit to not want to use ApiPlatform if you dislike it for any reason! However, we want to keep this bundle as simple as possible. In the Symfony ecosystem we have ApiPlatform as a very complete and continuously maintained product to create APIs ... so we can't spend our limited resources to create a simpler alternative ... which will be far worse and too limited. That's why I'm closing this proposal as "won't fix" but I hope you understand the reasoning of this decision.

I also want to thank you all for the discussion. It's great to be part of the Symfony community, where even "heated" debates like this are full of smart, well educated and reasoned comments. Thanks!
