### ISSUE TITLE
[proposal] add a default __toString method in entities

### ISSUE THREAD

**Issue by fabienlem** [symfony/maker-bundle#209]
Hello,

One common mistake when dealing with entities and relations through an admin bundle is to forget implementing the __toString method.

What about generating this method by default?

It could be something like this:

```php
    public function __toString()
    {
        return sprintf('%s #%d', __CLASS__, $this->getId());
    }
```

Thank you for your feedback.

Fabien

**Comment by weaverryan** [comment]
Hmm, I don’t know. You’re totally correct that this would be really nice for the EntityType in the form component. But I don’t like the idea of always adding the method, especially because we don’t really know how to implement it correctly in the generator (your idea is the best we could do, but it’s still not realistic). 

So I’m -1 - it does solve a problem, but I don’t think we’ll enough. It also makes it easy to accidentally render your entire object (e.g. in Twig), where you would now see the cryptic toString text instead of an error (and finding where this came from might be a challenge).

**Comment by stof** [comment]
And it can also create weird things for people using the `==` operator (which you might do in Twig if you use `==`), as the entity would then be equal to it string representation IIRC.
