### ISSUE TITLE
make:crud entity in a bundle

### ISSUE THREAD

**Issue by deankinns** [symfony/maker-bundle#212]
I'm trying to make CRUD for an entity in a local bundle.

$ php bin/console make:crud

 The class name of the entity to create CRUD (e.g. BraveGnome):
 > App\Acme\ThingBundle\Entity\Thing

In MakeCrud.php line 91:
                                                          
  Call to a member function getRepositoryClass() on null  

I have tried other formats for the name of the entity:
Acme:ThingBundle:Thing
ThingBundle\Thing
App:Acme:ThingBundle:Thing
App:Acme:ThingBundle:Entity:Thing
src/Acme/ThingBundle/Entity/Thing

these all return:

[ERROR] Entity "<attempted path>" does't exists.     
         Please enter existing one or create new                                

Can we use the command on entities outside the src/entities folder? it seems that the function prefixes the class with App\Entity\ unless the path is absolute but there is no way to provide an absolute path.

**Comment by javiereguiluz** [comment]
@deankinns I'm sorry you're facing issues when using this bundle. The reason is the same explained in [this comment](https://github.com/symfony/maker-bundle/issues/220#issuecomment-402962108): this bundle is only compatible with modern Symfony apps, so no app-bundles are supported.

We're not planning to support that feature, so for now, you'll need to keep using [SensioGeneratorBundle](https://symfony.com/doc/master/bundles/SensioGeneratorBundle/index.html) which provides almost the same features and works with that kind of app structure. Thanks!
