### ISSUE TITLE
make:crud to specific directory

### ISSUE THREAD

**Issue by gregurco** [symfony/maker-bundle#218]
Hello.
I didn't manage to fine if it's possible to do, but probably you can help me.
Is it possible to generate crud, but for admin. For example, I want controller to be in folder `src/Controller/Admin`?
Thanks.

**Comment by javiereguiluz** [comment]
Yes, you can do it as follows:

```bash
$ ./bin/console make:controller

 Choose a name for your controller class (e.g. DeliciousGnomeController):
 > Admin\UserController

 created: src/Controller/Admin/UserController.php

 Success!

 Next: Open your new controller class and add some pages!
```

**Comment by gregurco** [comment]
@javiereguiluz thanks for the reply, but it's about controller and not about CRUD.

**Comment by javiereguiluz** [comment]
Sorry! For the CRUD generator I'm afraid you can't select the destination directory. The reason is that we want to keep the CRUD generator super simple ... because there are a lot of community bundles that provide good CRUD generators.

The CRUD generated with this bundle is kind of useless (it doesn't have pagination, sorting or any other basic features) and at first we didn't even want to add a maker for this feature. I'm sorry!
