### ISSUE TITLE
Does maker-bundle support multiple bundle ?

### ISSUE THREAD

**Issue by KadioArnaud** [symfony/maker-bundle#220]
Hi all,

Since few days, the following doctrine command is not working `doctrine:generate:entities` the outputs state that the command is deprecated and suggest the maker-bundle. So i installed it. I notice that the bundle does not support multiple bundles or maybe i am doing things wrong.  The doc (link [https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html#configuration](url) ) says that you can configure _the root_ namespace. that sound weird because i don't use one namespace, i am still using the old phylosophy of multiple bundle, and i am getting my entities generated to wrong path.

Example when i confugure the following (i was just trying)
```

maker:
    root_namespace: Acme\Bundle
```

And run the following commande: `make:entity AcmeBlogBundle:Post`, i get the following

```
created: src/Acme/Bundle/Entity/AcmeBlogBundlePost.php
 created: src/Acme/Bundle/Repository/AcmeBlogBundlePostRepository.php
```

Does anybody know a doc or any reference ? Thanks

**Comment by javiereguiluz** [comment]
@KadioArnaud I'm sorry you are experiencing issues with this bundle. The reason is that this bundle only works when using the new way of developing modern Symfony apps (which requires not using bundles, following the same dir structure proposed by Flex and Symfony 4, etc.) and as you said, you are *"still using the old philosophy of multiple bundle"*.

I'm afraid we're not planning to make this bundle flexible enough to work with that "old philosophy" because we want to maintain it simple. That's why we're closing this issue as "won't fix".

For now, you'll need to keep using `doctrine:generate:entities`, which is deprecated, but still works. Thanks!
