### ISSUE TITLE
Warning: DOMElement::setAttribute(): string is not in UTF-8

### ISSUE THREAD

**Issue by pochy-ja** [symfony/maker-bundle#249]
After create a Controller this first error appear, but the file 

InventarioUbicaci�onController

in the controller places do not exist and in the console can not clear the cache, I try to erase the cache but the other error appears...

**FIRST**

WEBROWSER
```
(1/1)                                     ErrorException                                                                  Warning: DOMElement::setAttribute(): string is not in UTF-8
--
in XmlDumper.php line 101
at XmlDumper->addService(object(Definition), 'App\\Controller\\InventarioUbicaci�onController', object(DOMElement))in XmlDumper.php line 241
at XmlDumper->addServices(object(DOMElement))in XmlDumper.php line 53
at XmlDumper->dump()in ContainerBuilderDebugDumpPass.php line 32
at ContainerBuilderDebugDumpPass->process(object(ContainerBuilder))in Compiler.php line 95
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 736
at ContainerBuilder->compile()in Kernel.php line 519
at Kernel->initializeContainer()in Kernel.php line 123
at Kernel->boot()in Kernel.php line 183
at Kernel->handle(object(Request))in index.php line 37
```

**SECOND**

_CONSOLE_
```
In XmlDumper.php line 101:

  Warning: DOMElement::setAttribute(): string is not in UTF-8
```

**Comment by pochy-ja** [comment]
BTW, is a project with Symfony 4.1.3 in Ubuntu 16.04 with PHP 7.2.9-1+ubuntu16.04.1+deb.sury.org+1

**Comment by stof** [comment]
what is the command you ran exactly ?

**Comment by pochy-ja** [comment]
After

_./bin/console make:controller InventarioUbicacion_

that create a problem, then any command that i try to use, respond with the error

In XmlDumper.php line 101:

  Warning: DOMElement::setAttribute(): string is not in UTF-8

**Comment by weaverryan** [comment]
Hmm. After you ran the command, it did *not* create the controller class? It looks to me like the new controller maybe does exist, but Symfony is having a problem processing it because the class name has a special character that is causing issues. What files do you have in your controller directory? And, if you manually delete all the files in var/cache/dev/, does the error change?

Cheers!

**Comment by pochy-ja** [comment]
I erase the cache files but error persist, the problem is this, thanks @weaverryan, one special character in the name of the file but I coding from windows to a remote filesystem in Linux and from windows I do not see the files with the problem, I solve this, I conect to server Linux and erase the file with the caracter problem and it`s works again.

**Comment by nicolas-grekas** [comment]
We could detect that the input is not utf8 and either throw or convert it using the current locale.

**Comment by javiereguiluz** [comment]
@pochy-ja you said you run this command:

```
./bin/console make:controller InventarioUbicacion
```

but I guess you run this one instead, right?

```
./bin/console make:controller InventarioUbicación
```

**Comment by pochy-ja** [comment]
@javiereguiluz yes, that was the problem and I am agreed with a validation for this case!

**Comment by przemyslaw-bogusz** [comment]
While fixing this I ran into one more thing. Even if the string is UTF-8 encoded, [Str](https://github.com/symfony/maker-bundle/blob/master/src/Str.php]) has `asTwigVariable` method, which removes any unicode chars, and thus if you run:
```
./bin/console make:controller Ä --no-template
```
you get a controller with `@Route("//", name="_")`.

However, if you try just:
```
./bin/console make:controller Ä
```
you get an exception because `Str::asFilePath` uses method `underscore` from [Container](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Container.php), which applies `strtolower`, and thus messes up the string.

The big question is: should we exclude all unicode characters, or should we apply `mb_strtolower` in `Container` methods?
