### ISSUE TITLE
create entity property from make:entity --no-interaction 

### ISSUE THREAD

**Issue by tacman** [symfony/maker-bundle#269]
I think it'd be helpful be able to have the make:entity Command take all the arguments to create a single property from the command line.  This is especially helpful to condense documentation.  For example, the transcript provided here:

https://symfony.com/blog/introducing-symfony-panther-a-browser-testing-and-web-scrapping-library-for-php#testing-client-side-generated-html

Could be replaced with something like

```text
bin/console make:entity comment news string 255 no
bin/console make:entity comment body text no
```

Or perhaps there's already a way to answer a prompt from the command line?

**Comment by eco3** [comment]
Any update on this?

**Comment by tacman** [comment]
I've tried piping in the answers, but no luck.

     echo "Dummy\nno" | bin/console make:entity
     echo "Dummy" | bin/console make:entity
     "Dummy" | bin/console make:entity
     echo "Dummy -a" | bin/console make:entity  --no-interaction

 I've also tried creating a text file and piping it in

    bin/console make:entity < dummy.txt

In all cases, I'm getting

    Argument 1 passed to Symfony\Bundle\MakerBundle\Generator::createClassNameD  
  etails() must be of the type string, null given,

So maybe this question really belong in the Console issues, since it's fundamentally about having the ask() method to accept input from a pipe.

Of course, this bundle could be modified to create one field of an existing Entity, e.g.

      bin/console make:entity Dummy -a --no-interaction
      bin/console make:entity name=code --type=string --length=32 --nullable=false --no-interaction

**Comment by weaverryan** [comment]
Hi!

We've purposely not made this possible. This reason is that, if we allow `--no-interaction`, then the arguments & options of the command become part of the backwards-compatibility promise: if we decide we want to add a new argument to a maker or remove/rename an option, then we've actually broken BC, because this will break any automated scripts that you might now right using this.

Sorry, I know it's annoying - but the priority of the bundle is to be able to iterate and improve the generated code. The previous generator bundle (SensioGeneratorBundle) allowed this and suffered in how complex and bloated it got over time.

Cheers!

**Comment by tacman** [comment]
Okay, that makes sense as far as arguments and options.   

Maybe there's a solution to using stdin for ask(), I've just posted an issue in Console.

**Comment by weaverryan** [comment]
There might be - in our test suite, we actually use the Process component to interactively answer the questions: https://github.com/symfony/maker-bundle/blob/master/src/Test/MakerTestEnvironment.php#L208-L235
