### ISSUE TITLE
CRUD generator?

### ISSUE THREAD

**Issue by fabpot** [symfony/maker-bundle#3]
This bundle actually does not replace the current generator bundle as it was more focused on a CRUD generator. Is it something we want to do here as well?

**Comment by mneuhaus** [comment]
yes please :) 😃

**Comment by MarioBlazek** [comment]
It would be a nice feature to have +1

**Comment by ad3n** [comment]
Yes we need but with more clearly... Sensio Generator is ugly, redundant and repeated code anywhere

**Comment by ogizanagi** [comment]
How is the old CRUD generator used nowadays? I mean, isn't an admin CRUD generator like EasyAdmin more efficient & simpler? Or is it really used to bootstrap code in an application?
For my part, I never used the old CRUD generator.

**Comment by dsentker** [comment]
The crud Generator is used often in my projects. I would really love a modern crud Generator here. 
Btw i do not think that the sensio generator bundle creates 'ugly' Code.
+1 for a modern crud Generator 👌

**Comment by Leuloch** [comment]
I'm about to start a new project with symfony 4, and waiting for the CRUD generator feature! I'm a freelancer and this would help me a lot to bootstrap apps

**Comment by codedmonkey** [comment]
I like the idea of a CRUD generator, the old one provides enough basic utility for a functional starting point. When looking at the generated code, the PHP-code is just a basic Symfony controller, which seems fine. The templates on the other side, are something to be more opinionated about. Obviously it would be unwise to include CSS with the generated code and it would increase complexity for the user.

One solution to this could be a mechanic where third-party bundles are allowed to override the skeleton files (https://github.com/symfony/maker-bundle/issues/33). A dedicated bundle (like a Bootstrap bundle) would be able to provide more modern templates. The Bootstrap example is just one of the use cases, an official bundle would be unlikely to make everybody happy on this.

**Comment by lemorragia** [comment]
yesss!!

**Comment by inmarelibero** [comment]
I consider this an extremely important feature to have; "old" generator bundle does not provide ugly code, but it has come issue I personally handle very time I use it:
* can't choose in what folder generate the controller, form and templates
* different `new.html.twig` and `edit.html.twig` templates: first things I do is delete one of them and use the other for both `newAction()` and `editAction`
* rename variables in generated controller: `'edit_form'` => `form`, `$editForm` => `$form`
* remove delete form from edit template
* use uuid instead of id

so +1 for a new generator, hopefully extendable giving the possibility to the user to choose options above

**Comment by ksn135** [comment]
:+1: for CRUD

**Comment by kironet** [comment]
That would be great to have all important commands in one bundle. 👍

**Comment by lyrixx** [comment]
My 2 cents: If you need a basic CRUD generator, why don't you use EasyAdminBudle? It's so simple to set-up and to configure.

So for me, except for a training session, the CRUD generator is useless.

Anyway, This should be quite easy to develop it, But only if we support 0 options (we should only support Doctrine + Twig + no pagination + no filtering)

**Comment by javiereguiluz** [comment]
When someone mentions "CRUD generator", we think about the old symfony 1 admin generator or SonataAdmin, etc. But we can't make that because:

* If we make complex templates (the ones you need in a real app) then we'll complicate the MakerBundle a lot and we're repeating the work done by third-party bundles;
* If we make simplistic templates (like the ones generated by SensioGenerator) then that's useless in a real app: you don't even get pagination for listings!!

However, we could forget about the templates and other resources and **only generate the controller part**. This could be similar to the Rails routing resources. For example, if you put `resources :photos` in the Rails routing file ... you get a full controller to manage photos:

![rails-resources](https://user-images.githubusercontent.com/73419/33557198-e04380b0-d906-11e7-9db5-bb62db187fd6.png)

See http://guides.rubyonrails.org/routing.html for details.

**Comment by fabpot** [comment]
CRUD != admin generator. There is nothing in common between the 2. A CRUD generator is something that give you some code for you to modify. You own the code. And admin gen is something that let's you configure some generic code that you don't own.

We do have admin gens, and SensioGeneratorBundle is a CRUD generator. The latter is what we should replace.

**Comment by mneuhaus** [comment]
another approach to reduce the CRUD boilerplate could be something similar to [Djangos Class Based Views](https://docs.djangoproject.com/en/2.0/ref/class-based-views/).
Has something like this been considered before to reduce some boilerplate?

**Comment by ksn135** [comment]
In the past:
sf 1.x – built-in admingenerator
sf 2-3 – [symfony2admingenerator/GeneratorBundle](https://github.com/symfony2admingenerator/GeneratorBundle)  based on "deprecated" SensioGeneratorBundle 
@fabpot What should I do NOW to build and maintain enterprise system with many DB tables with **Symfony 4** ? Is there some receipt for **Flex** to generate complex templates and code (mean option 1 from @javiereguiluz 's [comment](https://github.com/symfony/maker-bundle/issues/3#issuecomment-348976558)) ?

**Comment by fabpot** [comment]
@ksn135 Not sure I understand your comment here. In Symfony 4, you have several admin generators... which are different from CRUD generation (see my previous comment).

**Comment by chepeftw** [comment]
I vote in favor of CRUD 😁
I think that the CRUD functionality is somehow important, first of all, it provides a solid ground for new devs for Symfony because it does not matter how explained you have something in the docs, if there are not meaningful examples then not everybody will fully understand what they are reading, but examples work most of the time and CRUD provides an easy way of devs generating their own skeletons as examples and from there pivot to more advanced stuff.
Second, one thing is admin generator bundle and one thing is to generate a basic HTML to start coding specific functionality. As @fabpot explained before. For experienced devs I think is useful since it saves you some time, some might argue that its "ugly" HTML but you can customize it by overriding the existing "ugly" HTML, others might argue that you could do it yourself, but once again it saves time, it provides an easy way to generate a good skeleton and then focus on what really matters.

**Comment by codedmonkey** [comment]
It sounds like this is the first thing people are missing when experimenting with Symfony 4. I think that in addition to @fabpot's argument, it's important to point out that we're trying to make it as easy as possible to create your own makers. Anybody who wants to customize the output for the CRUD generator is free to do so and could even publish it as a bundle. Built-in makers should remain as simple as possible.

**Comment by gonzakpo** [comment]
The idea is to have a single controller, views, etc., from which the generated code extends.
For example:
https://github.com/MWSimple/AdminCrudBundle

**Comment by mreichstadt** [comment]
Hi everybody,
I vote YES!!!! for this because:
- generator creates templates (ok ugly but at least files are created)
- generator creates all the methods (add, edit, show, delete) 
- generator creates the forms

In some of my apps, I have around 100 tables, and it's very useful for me to generate the crud for all my tables and then juste customize the twig part. Without that option, it would increase the time needed to develop it.

Other thing that is not linked, is it possible to add fields to an entity without having to get through the PHP file as we used to do in sf3 with command line?

**Comment by 8mccm8** [comment]
Hi all,

just to let me know, with symfony flex 3.4.2, I can't use the SensioGeneratorBundle and I must use maker-bundle! but I can't generate a CRUD Controller Based on a Doctrine Entity with  maker-bundle like this => "php bin/console generate:doctrine:crud"
I'm missing something but what!!?
thx

**Comment by Gonzalo1987** [comment]
I'd love to have a generator of a template like generate:doctrine:crud... and I'd love that make:entity works like generate:doctrine:entity and request the entity's fields and generate the annotations for that entity...

I feel that in S4 I need write more code than in the previous versions.

Greetings!

**Comment by dsentker** [comment]
@fabpot , most of us may have realized that a CRUD generator is not an admin generator. Regardless, I'm assuming that a CRUD entity generator will make life easier for many developers. Are there concrete plans to integrate something like this?

**Comment by javiereguiluz** [comment]
We are going to add an entity generator and we are probably going to add a CRUD generator like in the old SensioGeneratorBundle. When? No estimate date. We don't have enough resources to do all the things we want to do.

**Comment by mreichstadt** [comment]
It's possible and easy to create your own crud generator, as I did for some of my projects. This is not a "bundle" but a small set of programs I launch like this: php bin/createForm. For the moment it generates all the CRUD with either a very simple template (like it was done before) or a self-made template we use in our company.

**Comment by sadikoff** [comment]
Hi all. 

Need your advise. I have working crud generator as extension to maker-bundle, but for now generated code is not very beautiful. I can continue working on the bundle, if it is needed. But I don't  know what is the best solution for generated code.

**Comment by weaverryan** [comment]
@sadikoff the best solution might be to apply your code directly to this bundle and create a PR for the CRUD generation :). If you want to put in some work to build this command, we can help you and it will get done much faster.

**Comment by sadikoff** [comment]
@weaverryan thx I'll prepare PR for this feature tomorrow.
