### ISSUE TITLE
If you try to create a new entity with the name "Class" the console crashes

### ISSUE THREAD

**Issue by jger** [symfony/maker-bundle#305]
**Symfony version(s) affected**: x.y.z
Symfony Installer version 1.5.11

**Description**  
If you try to create a new entity with the name "Class" the console crashes

**How to reproduce**  
 ./bin/console ma:ent
Class name of the entity to create or update (e.g. GentleGnome):
 > Class
 created: src/Entity/Class.php
 created: src/Repository/ClassRepository.php

In Class.php line 10:
                                                                               
  syntax error, unexpected 'Class' (T_CLASS), expecting identifier (T_STRING)  

(and if you try again)
./bin/console ma:ent
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, ...

**Possible Solution**  
Don't allow the name Class for new entity 
**Additional context**

**Comment by SerkanYildiz** [comment]
Hi @jger,

This happens because you have used a [reserved keyword](https://secure.php.net/manual/en/reserved.keywords.php) defined by php.

The validator class in MakerBundle just checks if the classname starts with a letter or underscore, followed by any number of letters, numbers, or underscores.

I can provide a fix for this issue if you're interested.

ping @weaverryan

**Comment by xabbuh** [comment]
It's probably a good idea to take a look at http://docs.php.net/manual/en/reserved.php for a list of other reserved words.

**Comment by SerkanYildiz** [comment]
@xabbuh Thanks for the suggestion. I've created a PR. Could you take a look?
