### ISSUE TITLE
[DX] Usage of the Kernel for doc generation

### ISSUE THREAD

**Issue by noniagriconomie** [symfony/maker-bundle#35]
Hi
Could it be great to use the constant in
https://github.com/symfony/http-kernel/blob/master/Kernel.php (MAJOR|MINOR_VERSION)
to change the value of "current" in https://github.com/symfony/maker-bundle/blob/master/src/Command/MakeEntityCommand.php#L69
could define it in the abstractcommand and use it in the subcommand ?

so that it is a real link depending on the dev sf version :)

**Comment by javiereguiluz** [comment]
Thanks for proposing this change! This would indeed be more precise. However, according to the symfony.com traffic stats, more than 90% of Symfony Docs pageviews use `current` as their version, so people seem OK with that.

Moreover, we are discussing in the Symfony Docs team some ways to make docs easier to manage for us: one of those ideas is to stop updating old versions and just focus on `current`. No decision has been made yet, but as you can see, using `current` is the only future-proof version for the moment. That's why I'm closing this for now, but we'll probably reconsider this idea in the future. Thanks!

**Comment by noniagriconomie** [comment]
@javiereguiluz understood
beeing focused on current is they to go, but do not forget user using LTS! :)
Cheers
