### ISSUE TITLE
Can't install with Doctrine Cache Bundle

### ISSUE THREAD

**Issue by grisendo** [symfony/maker-bundle#415]
Hi!

I have a project (Symfony 3.4) where I want to add Symfony Maker Bundle, and I have a conflict when installing it

```
$ composer require symfony/maker-bundle --dev
...
    - symfony/maker-bundle v1.11.0 requires doctrine/inflector ^1.2
...
```
This is because I also have Doctrine Cache Bundle, and it needs doctrine/inflector 1.0

```
$ composer depends doctrine/inflector
doctrine/common                 v2.7.3  requires  doctrine/inflector (1.*)   
doctrine/doctrine-cache-bundle  1.3.2   requires  doctrine/inflector (~1.0)  
```
Anyone faced this problem?

Thanks in advance!

**Comment by pluseg** [comment]
@grisendo Hi! In fact, it's not a problem of MakerBundle, it's a dependency management routine. Try to update all these packages (or `doctrine/inflector` at least) along with installing `symfony/maker-bundle`. From the text above I don't see any conflicts, because of `1.*` and `~1.0` includes `^1.2`, hence `composer update` of  `doctrine/inflector` should help.

Cheers!

**Comment by grisendo** [comment]
Oops, you are right... reading this https://getcomposer.org/doc/articles/versions.md#tilde-version-range-

The problems were (I think):
* After the conflict, I tested https://semver.npmjs.com/ which says doctrine/inflector ~1.0 only matches with 1.0.0, 1.0.1 and 1.0.2, which now I see it's wrong, according to what you say.
* My last composer update was made with PHP 5.6, so composer didn't try with doctrine/inflector 1.2/1.3 (both require PHP7). I tried to add symfony/maker-budle via "composer require" with PHP7.1, but somehow, it didn't launch composer update! _Installation request for doctrine/inflector (locked at v1.1.0)_. Anyway, it's not a problem with this package, as you say.

Thanks a lot!
