### ISSUE TITLE
Do not replace json by json_array when making an Entity

### ISSUE THREAD

**Issue by vbourdeix** [symfony/maker-bundle#447]
When I create an entity with make:entity and type json for the type of a field, it is replaced by json_array, which is deprecated since Doctrine 2.6 if I remember well.

There already has been a pull request to remove the support to json_array, yet I have this behaviour. When I look at the code, the only place (inside the MakerBundle) I can found the json_array string is in src/GeneratorTwigHelper.php but I don't know if this is related, because if there is a possibility of extending the types managed by the maker bundle (didn't search deep enough to know), this behaviour could come from another bundle.

As a side note, the json_array is displayed among the "Other Types" section.

**Comment by LeJeanbono** [comment]
It's due to the autocomplete :
![json_array](https://user-images.githubusercontent.com/11347342/61598852-253b8000-ac23-11e9-902c-9f12628d6714.JPG)
If yout type `Enter`, `json_array `is filled instead of `json`

Autocomplete is based on `Doctrine\DBAL\Types\Type` and `json_array ` is before `json` that's why he's trigger before

**Comment by vbourdeix** [comment]
Then it would be a good idea to remove json_array of the possibilities, right ? If necessary I can make a pull request for this.

**Comment by romaricdrigon** [comment]
As explained on #448, I fully agree with @vbourdeix 
Help needed to remove `json_array` from the types :)

**Comment by LeJeanbono** [comment]
@romaricdrigon I will ;)
