### ISSUE TITLE
Missing setter method on non-self-incrementing primary key

### ISSUE THREAD

**Issue by zacharyzh** [symfony/maker-bundle#465]
**Symfony version(s) affected**: 4.3.3

**Description**  

I configured the primary key as non-self-incrementing. Then after running the make:entity command and I found that the setter method is missing.

    # config/packages/doctrine.yaml
    doctrine:
        orm:
            type: yml
            dir: '%kernel.project_dir%/config/orm'

The entity definition:

    # config/orm/User.orm.yml
    App\Entity\User:
        type: entity
        table: app_user
        id:
            id:
                type: integer
                nullable: false
                options:
                    unsigned: true
        fields:
            name:
                type: string
                length: 32
                nullable: false

The User class after generating:

    class User
    {
        protected $id;
        protected $name;
    
        public function getId(): ?string
        {
            return $this->id;
        }

        // missing setter method here.

        public function getName(): ?string
        {
            return $this->name;
        }
    
        public function setName(string $name): self
        {
            $this->name = $name;
    
            return $this;
        }
    }

**How to reproduce**  

Here is an example: [https://github.com/zacharyzh/sf-make-bundle-issue](https://github.com/zacharyzh/sf-make-bundle-issue)

**Comment by xabbuh** [comment]
@zacharyzh FYI, I have moved the issue as the MakerBundle has its own repository.

**Comment by zacharyzh** [comment]
@xabbuh 

Thank you.

**Comment by Pierstoval** [comment]
Why would one need a setter for the id? If it's non-self-incrementing, it means you should have it in the constructor, or just not in the code and delegate its generation to the database

**Comment by pbowyer** [comment]
> Why would one need a setter for the id?
Because the Symfony ecosystem is based around getters/setters being present?

If I use https://github.com/hautelook/AliceBundle and my entities have natural keys, I have to add a setter for that. It doesn't go "Oh there's a constructor argument, I'll use that".

I'm not saying it's good, just how it is. It should be in the constructor, but MakerBundle is pragmatic and works with where we are.

**Comment by zacharyzh** [comment]
Many asian languages (like CJK) could be converted to latin alphabets and use as the ID, and this conversion process is usually done by a service. So define a setter method here is helps to keep the entity class simple.

Example:

    /**
     * A common situation is:
     * the tag id is dependent on the tag name and converted by a custom service.
     */
    $tagId = $this->convertService->convertToAlphabets($tag->getName());
    $tag->setId($tagId);

**Comment by Pierstoval** [comment]
Yours are very specific case. In 6 years of Symfony with lots of projects, small and big, I never had any case where I couldn't use the constructor instead.

I think the "need" for a setter for the id field is a marginal case and we can skip it. After all, any good IDE allows you to freely create this in one keyboard shortcut or a few clicks, so I think we should **not** promote setting IDs in entities.

> Because the Symfony ecosystem is based around getters/setters being present?

The Symfony ecosystem is based around getters&setters mostly because the Form component (and PropertyAccess) make a high use of them. If we remove them, we just use proper patterns (DTOs & stuff) in order to manage the state for our objects.

It has been said countless times that getters&setters are not a good practice, and having them in the make command is IMO already a lot and we should not promote more than there already is about these practices.

**Comment by stof** [comment]
Thus, a setter would make it possible to *mutate* the id, which is quite a bad idea.

**Comment by zacharyzh** [comment]
I understand. Thank you for taking time.
