### ISSUE TITLE
Add setter for $namespacePrefix in the Generator

### ISSUE THREAD

**Issue by bhorovyi** [symfony/maker-bundle#470]
Hi!

I tried to create custom maker which could allow me to create entity and repository in different namespaces;

I can pass absolute path in command like: `make:entity \\App\\CustomDirectory\\Entity\\EntityClass`, but Repository still created in default symfony directory.

Yes, I can change route_namespace in maker.yaml file but if it were possible to set $namespacePrefix in Generator class, we could dynamically changing namespace and create Entity and Repository where we wont.

**Comment by weaverryan** [comment]
Hi @bohdan-gorovoy!

Can you tell me a bit more about exactly what you want to accomplish? Is the only issue that when you create a custom namespace for your entity (e.g. `App\\CustomDirectory\\Entity\\EntityClass` ) that the repository is generated in the "standard" place (and you would probably want it in `App\\CustomDirectory\\Repository\\EntityClassRepository`)? Or do you need to create a fully-customized maker for some other reason?

**Comment by bohdan-gorovoy** [comment]
Hi @weaverryan 
For example, I want to divide my code into different components (src\Component\Component1, src\Component\Component2, ...), and I want each of my components has his own Entity and Repository. 
So I tried to create my own maker for creating Entity and Repository in different folders (src\Component\Component1\Entity, src\Component\Component2\Entity, ...) but now I can't do it, because of namespace statically wrote in *.yaml file.

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
