### ISSUE TITLE
Generating  entity/crud in other format like annotation ?

### ISSUE THREAD

**Issue by Pablossoo** [symfony/maker-bundle#489]
Hello, 

I would like generating entity in yml or xml format instead of annotation. Is it possible?  I tried

**Comment by romaricdrigon** [comment]
Hello,

YAML mappings in Doctrine are deprecated ; they will be dropped by Doctrine 3.
XML mappings is a mildly advanced use case, since Symfony best practice is to [use annotations](https://symfony.com/doc/current/best_practices.html#use-annotations-to-define-the-doctrine-entity-mapping). I don't think it should be an option in MakerBundle, the goal here is more simplicity rather than unlimited configuration & to fine-tune it to your taste.

**Comment by mtyeh411** [comment]
i personally find annotation mappings to be a clear violation of SOLID principles and i would guess that i'm not alone in that thought despite it being best practice by Symfony.

imho i would like to see better synergy between MakerBundle & DoctrineBundle wherein MakerBundle is able to detect the doctrine.yaml mapping config.  MakerBundle loses its usefulness if the entities it's helping to generate don't even match how they are configured to be used within Symfony.

it's a shame as i believe that the command line prompts provided by MakerBundle make the tedious, error-prone exercise of writing XML files a far better user/dev experience.
