### ISSUE TITLE
make:entity non interactive

### ISSUE THREAD

**Issue by fox91** [symfony/maker-bundle#523]
I state that I am relatively new to using Symfony and the MakerBundle.

I can't find a way to use the `make:entity` command to add properties without interactivity.
I will be used to working with the CLI, but I think it is much faster for the user if the possibility of using non-interactive commands is offered to do the same operations that are proposed interactively.

For example, now I am forced to do these operations:

```bash
php bin/console make:entity --no-interaction VictoriousKangaroo
# use awk command to insert first and last name proprieties
# in correct position with correct annotations
php bin/console make:entity --regenerate 'App\Entity\VictoriousKangaroo'
```

While it would be much more convenient not to have to disconnect from the terminal and be able to complete the creation of your Entities in a way similar to this:

```bash
php bin/console make:entity --no-interaction VictoriousKangaroo
php bin/console make:entity:propriety --no-interaction \
  --name name \
  --type string \
  --length 255 \
  --not-nullable \
  VictoriousKangaroo
php bin/console make:entity:propriety --no-interaction \
  --name age \
  --type integer \
  --nullable \
  VictoriousKangaroo
```

It seems to me that this mode is missing from the whole bundle.

Is it a feature already present in the roadmap, or would you be interested in inserting it?

**Comment by jrushlow** [comment]
howdy @fox91 thanks for the feedback! Unfortunately we try to stay away from command arguments as much as possible. By asking questions, this allows users to see changes that may have occurred to a particular maker since the last time they used it. We are consistently adding new functionality to the existing makers, and sometimes this means changing the order in which information is collected. But above all it provides the user better visibility and context for the makers and their options.
