### ISSUE TITLE
Make:entity with XML and YML mapping?

### ISSUE THREAD

**Issue by theredled** [symfony/maker-bundle#563]
I was using `doctrine:generate:entity` until it disappeared, which I just found out. 
From what I read, maker-bundle and `make:entity` is the only current alternative.

But I'm using XML format, and it seems that only annotations are available with `make:entity`:
```
[ERROR] Only annotation mapping is supported by make:entity, but the                                                   
         <info>App\Entity\QsGeneralBundle\Entity\AccountAvatar</info> class uses a different format. If you would like  
         this command to generate the properties & getter/setter methods, add your mapping configuration, and then      
         re-run this command with the <info>--regenerate</info> flag.                                                   
```

Is there a chance it can ever implement XML and YAML schemas ?
Or more generally, all the features of the late `doctrine:generate:entity`?

Maybe I'm using the wrong tool?

Many thanks.

**Comment by weaverryan** [comment]
Hi @theredled!

I didn't implement it because annotations are what most people use and that command was a LOT of work just for annotations ;). Here's what we *do* support (mentioned in the comment, but here it is said a bit differently):

A) add the new field in your YAML or XML file
B) Run `make:entity --regenerate` and it will update your classes with the new properties, getter/setters, etc

I'm not against adding one for YAML - we do have a `YamlSourceManipulator` that's capable of updating YAML without removing comments and formatting - but YAML is also deprecated in Doctrine 3.0. For XML, there is currently no way for us to update an XML file without completely removing any formatting or comments you may have inside. So that would not be reasonably possible right now.

Cheers!

**Comment by theredled** [comment]
Thanks for your answer!

> For XML, there is currently no way for us to update an XML file without completely removing any formatting or comments you may have inside. So that would not be reasonably possible right now.

But `doctrine:generate:entity` was able to do that, isn't it?

**Comment by weaverryan** [comment]
> But `doctrine:generate:entity` was able to do that, isn't it?

This command could only *create* a new class. It was not capable of also updating the classes later. So, creating a *new* XML file is easy. But *updating* an XML file (like when you're using `make:entity` to add a new field) without killing your comments or whitespace would be challenging. We built a class to do it for YAML (and it's *huge*), but I don't have a lot of interest to do it for XML, because it's not as commonly used (sorry!).

Cheers!

**Comment by theredled** [comment]
> This command could only _create_ a new class. It was not capable of also updating the classes later. So, creating a _new_ XML file is easy. But _updating_ an XML file (like when you're using `make:entity` to add a new field) without killing your comments or whitespace would be challenging. We built a class to do it for YAML (and it's _huge_), but I don't have a lot of interest to do it for XML, because it's not as commonly used (sorry!).

All right so as I understand, new features (creating a new field) needed to discard old ones (generating XML).

Just to justify myself for using XML, I think it's a bad practice to merge layers like Symfony model logic and Doctrine model logic - and also, it makes much bigger files.

**Comment by weaverryan** [comment]
> Maybe XML support could be limited to creating new entities?
> Like, more generally, keeping XML/YAML support for easily automatable (and manually costly)
> operations, while adding more advanced features to annotations only?
> Maybe it would even save you from maintaining YAML advanced features?

I'm not against doing some more for XML. But I won't create it :). It's just a matter of time - I have short time, so I have to prioritize on features that the "majority" of people use (that's not at all to say that XML is wrong - it's a *perfectly* valid preference, but it's used by many fewer people).

If you're interested, you could create a PR :).

Cheers!

**Comment by theredled** [comment]
Right, I'll do it if I also find time. Thanks!

**Comment by cosminsandu** [comment]
@theredled did you create any PR for this?
