### ISSUE TITLE
make:entity --regenerate crash if class name is Match

### ISSUE THREAD

**Issue by bettinz** [symfony/maker-bundle#654]
Hello, I'm doing for a soccer project entities like `team` and `match`

I usually use the command `php bin/console make:entity --regenerate` to create setters and getters when I add some fields to the entity.
After last updates, the class `Match` stopped working with this error:

`  Syntax error, unexpected T_MATCH, expecting T_STRING on line 40  
`

on Line 40 I've

```php
class Match {


```

Is that a reserved word? This is only happening with latest versions of maker bundle. 

Thanks ;)

**Comment by LeJeanbono** [comment]
Can you try to rename your entity class (like `Meet`) and use the annotation `@Table(name="match")`  ?

**Comment by bettinz** [comment]
Hello, I've tried renaming the entity `SingleMatch` and it works as expected. So I guess the bug was with class name. Can you confirm it?

**Comment by LeJeanbono** [comment]
If you use MySQL, `MATCH` is a reserved keyword :
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-M

**Comment by bettinz** [comment]
Ok, so this is the issue, thank you. Do you know why with previous versions of maker bundle it was working?

Thanks

**Comment by LeJeanbono** [comment]
`MATCH` get reserved with MySQL8, did you upgrade ?

**Comment by bettinz** [comment]
I don't think so, my version was 8 before the error. The only upgrade that I made is with maker bundle. In the next few days I'll try an older version and test this 😉

**Comment by gonssal** [comment]
Just been hit by this issue, and it has nothing to do with SQL keywords. The problem is [this](https://github.com/nikic/PHP-Parser/issues/715).

Considering how usual the match word is, I'd say more reports will be coming on this one until people upgrades to PHP8 and have to actually fix the names.

maker-bundle could start the parser with the same PHP version the user is using to avoid this issue, not sure if a good idea though.
