### ISSUE TITLE
 Suggestion for `make:entity`: New option for auto migration

### ISSUE THREAD

**Issue by art-cg** [symfony/maker-bundle#804]
Instead of these 3 steps i suggest a new option for a direct generation and migration.
php bin/console make:entity
php bin/console make:migration
php bin/console doctrine:migrations:migrate

Suggestion:
php bin/console make:entity **--migrate**
With this option the other 2 steps are executed automatically.

Internal this could call php bin/console make:migration --migrate
Which is calling symfony console doctrine:migrations:migrate

**Comment by jrushlow** [comment]
Howdy @art-cg It's not a bad idea. My only concern is would this pollute your migrations and cause a mess when you generate the entity and then need to immediately update the meta data for the entity.

As an example, I would not be able to utilize this in any of my projects because I use UUID's for my entity ID / PK's. More often than not, I also implement a custom strategy for the ID generation. 

On the flip side to that, if this were to be implemented, I think it would be better to ask `Do you want to generate / run a migration for this entity after its created?` within `make:entity`'s interaction steps.

**Comment by art-cg** [comment]
Hi @jrushlow . It is optional. Could be pollute the migrations. In my case while developing i often change things, and later remove the migrations and generate it new. So this is not a problem in my case. I don't know how others developer handle this.
To add this option as an question is a good idea.

If you want to add uuid by the entity, this is a common task. This should be another Input question / parameter. Meanwhile Symfony has it own UUID-Generator, so this should be easier. The custom strategy for the ID generation is indeed a reason to not use this option in your case.

**Comment by jrushlow** [comment]
We have no immediate plans to implement this into MakerBundle. However, PR's are always welcome!
