### ISSUE TITLE
Symfony UX: make Stimulus controller

### ISSUE THREAD

**Issue by dunglas** [symfony/maker-bundle#809]
It would be nice for discoverability to add a command to create a Stimulus controller. I suggest adding a new maker called `make:stimulus-controller` generating a JS file and the corresponding Twig template loading the controller.

Related to https://github.com/symfony/recipes/pull/891 and https://github.com/symfony/recipes/pull/890.

WDYT @weaverryan @tgalopin?

**Comment by tgalopin** [comment]
Does it make sense to create a Twig template? I feel it would make more sense to display a snippet of HTML in the console instead of creating a Twig template, as the controller will probably not be dedicated to a Twig template the same way a Symfony controller is.

**Comment by dunglas** [comment]
As a Stimulus controller is tight to an HTML element, maybe it could make sense to also generate the related Twig template, that will be used as a partial (`include` etc). We could also add a `--no-template` option (the Symfony Controller maker as a similar option).

**Comment by OskarStark** [comment]
Shall we name them make:ux:..... ?

**Comment by jrushlow** [comment]
> We could also add a --no-template option (the Symfony Controller maker as a similar option).

Instead of a flag, it would be better to ask this as question "Do you want to generate the templates...."(or something along those lines)  that defaults to `true`.

> Shall we name them make:ux:..... ? 

I think `make:stimulus` would be a bit more intuitive as that's what we are referring to.. But depending on how many other makers are foreseeable - `make:ux:stimulus` would also be a desirable path forward.

**Comment by JabriAbdelilah** [comment]
@dunglas I made a PR #1075
