### ISSUE TITLE
PHP8 annotations while not no dependency on PHP8

### ISSUE THREAD

**Issue by haassie** [symfony/maker-bundle#898]
Version: symfony/maker-bundle: 1.31.1
PHP locally: v8.0.3
PHP mandatory in composer.json: >=7.2.5

When you use `make:controller` function, it will create a PHP8-version of the annotation. For example: `#[Route('/', name: 'homepage')]` while the version in the composer manifest is 7.2.5 and higher.

Other make methods are still using the "old" version of the annotation. This might cause some issues isn't it?

**Comment by jrushlow** [comment]
Howdy @haassie Thanks for the question. When running MakerBundle commands that generate code, we determine the version of PHP to base the generated code off of in the following order:

1) If no `composer.lock` file is found, return the value of `PHP_VERSION`
2) If `composer.lock` exists and a platform override is specified in the `composer.json` file, we use that value.
3) Otherwise use the value of `PHP_VERSION`

I should also note that when determining whether or not we use attributes in the generated code - ultimately it comes down to if you're using (or the platform override is set to) PHP 8 or greater && you're using Symfony 5.2 or greater, we generate the code with attributes instead of annotations where possible.

We've updated as many makers as possible a while back to use the new PHP Attributes. The only area I believe we still need to implement attributes instead of annotations is Doctrine (Entities).

Going to close this for now, but please feel free to reply if you have any questions. Thanks again!

**Comment by jrushlow** [comment]
Ahh just in case someone doesn't know what PHP_VERSION is or how to set the platform override in their composer.json:

https://www.php.net/manual/en/reserved.constants.php

https://getcomposer.org/doc/06-config.md#platform

**Comment by nicolas-grekas** [comment]
That may be the issue actually: `PHP_VERSION` is unreliable. We should use `PHP_VERSION_ID` instead! Apple killed `PHP_VERSION` by making it unusable.
