### ISSUE TITLE
php bin/console make:migration --- Fatal Error -> May not inherit from final class

### ISSUE THREAD

**Issue by christianostrem** [symfony/maker-bundle#977]
Hi,

I need help with this issue.

I have symfony 5.3.7 and i get this error when trying to make a migration.
Command: php bin/console make:migration
I have the same vendor libraries as if you downloaded a new project skeleton from  symfony.

Iam also running php v. 8.x

```
PHP Fatal error:  Class Doctrine\Bundle\MigrationsBundle\Command\MigrationsDiffDoctrineCommand may not inherit from final class (Doctrine\Migrations\Tools\Console\Command\DiffCommand) in /srv/sites/dev/htdocs/vendor/doctrine/doctrine-migrations-bundle/Command/MigrationsDiffDoctrineCommand.php on line 20

In MigrationsDiffDoctrineCommand.php line 20:
                                                                                                                                                                                        
  Compile Error: Class Doctrine\Bundle\MigrationsBundle\Command\MigrationsDiffDoctrineCommand may not inherit from final class (Doctrine\Migrations\Tools\Console\Command\DiffCommand) 
```

**Debug info:**

**Filename:**
/vendor/doctrine/migrations/lib/Doctrine/Migrations/Tools/Console/Command/DiffCommand.php

final class DiffCommand extends DoctrineCommand
{
    /** @var string */
    protected static $defaultName = 'migrations:diff';

**Comment by weaverryan** [comment]
Hey!

I'm not sure how it's possible, but it seems like you somehow got a mixture of DoctrineMigrationsBundle 2.x and DoctrineMigrations 3.x. 

The `MigrationsDiffDoctrineCommand` class only exists in DoctrineMigrationsBundle 2.x. It was removed for DoctrineMigrationBundle 3.0. Also, the `DiffCommand` is only `final` starting in DoctrineMigrations 3.0.

So, DoctrineMigrationsBundle 2.x is incompatible with DoctrineMigrations 3.x. I think this is your problem. The mystery is that DoctrineMigrationsBundle 2.x *says* in its composer.json file that it only works with DoctrineMigrations 2.x (not 3.x) - https://github.com/doctrine/DoctrineMigrationsBundle/blob/2.2.x/composer.json#L26 - so I can't figure out exactly how you would have gotten these two versions mixed together.

Anyways, I'm going to close since this isn't related to MakerBundle.

Cheers!

**Comment by christianostrem** [comment]
I found the solution. I deleted the vendor folder and installed it again. It works now.
